# Build stage
FROM node:18-alpine AS builder

WORKDIR /app

# Install dependencies separately to leverage Docker cache
COPY package*.json ./
RUN npm ci

# Define build arguments (mapped in docker-compose.yml)
ARG REACT_APP_FIREBASE_API_KEY
ARG REACT_APP_FIREBASE_AUTH_DOMAIN
ARG REACT_APP_FIREBASE_PROJECT_ID
ARG REACT_APP_FIREBASE_STORAGE_BUCKET
ARG REACT_APP_FIREBASE_MESSAGING_SENDER_ID
ARG REACT_APP_FIREBASE_APP_ID
ARG REACT_APP_NASA_API_KEY
ARG REACT_APP_DISABLE_REGISTRATION
ARG REACT_APP_AURORA_FORECAST_NORTHERN_URL
ARG REACT_APP_AURORA_FORECAST_SOUTHERN_URL
ARG REACT_APP_SDO_BASE_URL
ARG REACT_APP_APOD_URL
ARG REACT_APP_KP_INDEX_URL
ARG REACT_APP_KP_FORECAST_URL
ARG REACT_APP_ALERTS_URL
ARG REACT_APP_MAGNETIC_FIELD_URL
ARG REACT_APP_ENABLE_PUSH_NOTIFICATIONS
ARG REACT_APP_ENABLE_SOLAR_IMAGES
ARG REACT_APP_ENABLE_OFFLINE_MODE

# Set them as environment variables so react-scripts can see them
ENV REACT_APP_FIREBASE_API_KEY=$REACT_APP_FIREBASE_API_KEY \
    REACT_APP_FIREBASE_AUTH_DOMAIN=$REACT_APP_FIREBASE_AUTH_DOMAIN \
    REACT_APP_FIREBASE_PROJECT_ID=$REACT_APP_FIREBASE_PROJECT_ID \
    REACT_APP_FIREBASE_STORAGE_BUCKET=$REACT_APP_FIREBASE_STORAGE_BUCKET \
    REACT_APP_FIREBASE_MESSAGING_SENDER_ID=$REACT_APP_FIREBASE_MESSAGING_SENDER_ID \
    REACT_APP_FIREBASE_APP_ID=$REACT_APP_FIREBASE_APP_ID \
    REACT_APP_NASA_API_KEY=$REACT_APP_NASA_API_KEY \
    REACT_APP_DISABLE_REGISTRATION=$REACT_APP_DISABLE_REGISTRATION \
    REACT_APP_AURORA_FORECAST_NORTHERN_URL=$REACT_APP_AURORA_FORECAST_NORTHERN_URL \
    REACT_APP_AURORA_FORECAST_SOUTHERN_URL=$REACT_APP_AURORA_FORECAST_SOUTHERN_URL \
    REACT_APP_SDO_BASE_URL=$REACT_APP_SDO_BASE_URL \
    REACT_APP_APOD_URL=$REACT_APP_APOD_URL \
    REACT_APP_KP_INDEX_URL=$REACT_APP_KP_INDEX_URL \
    REACT_APP_KP_FORECAST_URL=$REACT_APP_KP_FORECAST_URL \
    REACT_APP_ALERTS_URL=$REACT_APP_ALERTS_URL \
    REACT_APP_MAGNETIC_FIELD_URL=$REACT_APP_MAGNETIC_FIELD_URL \
    REACT_APP_ENABLE_PUSH_NOTIFICATIONS=$REACT_APP_ENABLE_PUSH_NOTIFICATIONS \
    REACT_APP_ENABLE_SOLAR_IMAGES=$REACT_APP_ENABLE_SOLAR_IMAGES \
    REACT_APP_ENABLE_OFFLINE_MODE=$REACT_APP_ENABLE_OFFLINE_MODE


# Copy source and build
COPY . .
# Keep memory limit for large builds and disable sourcemaps for speed
ENV NODE_OPTIONS="--max-old-space-size=4096"
RUN GENERATE_SOURCEMAP=false npm run build

# Production stage
FROM nginx:alpine

# Copy built files
COPY --from=builder /app/build /usr/share/nginx/html

# Copy custom nginx configuration
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
